create table "public"."job_difficulty_ratings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "rating" bigint not null,
    "slug" text not null
);


create table "public"."jobs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "posted_by_id" uuid not null,
    "title" text not null,
    "description" text not null,
    "min_budget" bigint not null,
    "updated_at" timestamp with time zone default now(),
    "difficulty_rating_id" bigint not null,
    "max_budget" bigint not null,
    "decided_price" bigint,
    "decider_id" uuid,
    "worker_id" uuid,
    "status_id" bigint not null
);


create table "public"."payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "payee_id" uuid not null,
    "approver_id" uuid not null,
    "job_id" bigint not null,
    "status_id" bigint not null
);


create table "public"."proposals" (
    "id" bigint generated by default as identity not null,
    "proposer_id" uuid not null,
    "job_id" bigint not null,
    "title" text not null,
    "description" text not null,
    "status_id" bigint not null default '3'::bigint,
    "created_at" timestamp with time zone not null default now(),
    "acceptor_id" uuid
);


create table "public"."statuses" (
    "id" bigint generated by default as identity not null,
    "type" text not null,
    "title" text not null,
    "slug" text not null,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."user_profiles" (
    "name" character varying,
    "email" character varying,
    "created_at" timestamp(6) without time zone not null default now(),
    "updated_at" timestamp(6) without time zone not null default now(),
    "avatar_url" text,
    "id" uuid not null,
    "account_balance" double precision not null default '0'::double precision,
    "role_id" bigint not null default '1'::bigint,
    "status_id" bigint not null default '1'::bigint
);


create table "public"."user_roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "slug" text not null
);


create table "public"."withdrawal_requests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "status_id" bigint not null,
    "amount" bigint not null,
    "requestor_id" uuid not null,
    "approver_id" uuid
);


CREATE UNIQUE INDEX index_users_on_email ON public.user_profiles USING btree (email);

CREATE UNIQUE INDEX job_difficulty_ratings_pkey ON public.job_difficulty_ratings USING btree (id);

CREATE UNIQUE INDEX job_difficulty_ratings_rating_key ON public.job_difficulty_ratings USING btree (rating);

CREATE UNIQUE INDEX jobs_pkey ON public.jobs USING btree (id);

CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id);

CREATE UNIQUE INDEX proposals_pkey ON public.proposals USING btree (id);

CREATE UNIQUE INDEX statuses_pkey ON public.statuses USING btree (id);

CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (id);

CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);

CREATE UNIQUE INDEX withdrawal_requests_pkey ON public.withdrawal_requests USING btree (id);

alter table "public"."job_difficulty_ratings" add constraint "job_difficulty_ratings_pkey" PRIMARY KEY using index "job_difficulty_ratings_pkey";

alter table "public"."jobs" add constraint "jobs_pkey" PRIMARY KEY using index "jobs_pkey";

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";

alter table "public"."proposals" add constraint "proposals_pkey" PRIMARY KEY using index "proposals_pkey";

alter table "public"."statuses" add constraint "statuses_pkey" PRIMARY KEY using index "statuses_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY using index "user_profiles_pkey";

alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";

alter table "public"."withdrawal_requests" add constraint "withdrawal_requests_pkey" PRIMARY KEY using index "withdrawal_requests_pkey";

alter table "public"."job_difficulty_ratings" add constraint "job_difficulty_ratings_rating_key" UNIQUE using index "job_difficulty_ratings_rating_key";

alter table "public"."jobs" add constraint "jobs_decider_id_fkey" FOREIGN KEY (decider_id) REFERENCES user_profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."jobs" validate constraint "jobs_decider_id_fkey";

alter table "public"."jobs" add constraint "jobs_difficulty_rating_id_fkey" FOREIGN KEY (difficulty_rating_id) REFERENCES job_difficulty_ratings(id) ON UPDATE CASCADE not valid;

alter table "public"."jobs" validate constraint "jobs_difficulty_rating_id_fkey";

alter table "public"."jobs" add constraint "jobs_posted_by_id_fkey" FOREIGN KEY (posted_by_id) REFERENCES user_profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."jobs" validate constraint "jobs_posted_by_id_fkey";

alter table "public"."jobs" add constraint "jobs_status_id_fkey" FOREIGN KEY (status_id) REFERENCES statuses(id) ON UPDATE CASCADE not valid;

alter table "public"."jobs" validate constraint "jobs_status_id_fkey";

alter table "public"."jobs" add constraint "jobs_worker_id_fkey" FOREIGN KEY (worker_id) REFERENCES user_profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."jobs" validate constraint "jobs_worker_id_fkey";

alter table "public"."payments" add constraint "payments_approver_id_fkey" FOREIGN KEY (approver_id) REFERENCES user_profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_approver_id_fkey";

alter table "public"."payments" add constraint "payments_job_id_fkey" FOREIGN KEY (job_id) REFERENCES jobs(id) ON UPDATE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_job_id_fkey";

alter table "public"."payments" add constraint "payments_payee_id_fkey" FOREIGN KEY (payee_id) REFERENCES user_profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_payee_id_fkey";

alter table "public"."payments" add constraint "payments_status_id_fkey" FOREIGN KEY (status_id) REFERENCES statuses(id) ON UPDATE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_status_id_fkey";

alter table "public"."proposals" add constraint "proposals_acceptor_id_fkey" FOREIGN KEY (acceptor_id) REFERENCES user_profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."proposals" validate constraint "proposals_acceptor_id_fkey";

alter table "public"."proposals" add constraint "proposals_job_id_fkey" FOREIGN KEY (job_id) REFERENCES jobs(id) ON UPDATE CASCADE not valid;

alter table "public"."proposals" validate constraint "proposals_job_id_fkey";

alter table "public"."proposals" add constraint "proposals_proposer_id_fkey" FOREIGN KEY (proposer_id) REFERENCES user_profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."proposals" validate constraint "proposals_proposer_id_fkey";

alter table "public"."proposals" add constraint "proposals_status_id_fkey" FOREIGN KEY (status_id) REFERENCES statuses(id) ON UPDATE CASCADE not valid;

alter table "public"."proposals" validate constraint "proposals_status_id_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_id_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES user_roles(id) ON UPDATE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_role_id_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_status_id_fkey" FOREIGN KEY (status_id) REFERENCES statuses(id) ON UPDATE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_status_id_fkey";

alter table "public"."withdrawal_requests" add constraint "withdrawal_requests_approver_id_fkey" FOREIGN KEY (approver_id) REFERENCES user_profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."withdrawal_requests" validate constraint "withdrawal_requests_approver_id_fkey";

alter table "public"."withdrawal_requests" add constraint "withdrawal_requests_requestor_id_fkey" FOREIGN KEY (requestor_id) REFERENCES user_profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."withdrawal_requests" validate constraint "withdrawal_requests_requestor_id_fkey";

alter table "public"."withdrawal_requests" add constraint "withdrawal_requests_status_id_fkey" FOREIGN KEY (status_id) REFERENCES statuses(id) ON UPDATE CASCADE not valid;

alter table "public"."withdrawal_requests" validate constraint "withdrawal_requests_status_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.user_profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$function$
;

grant delete on table "public"."job_difficulty_ratings" to "anon";

grant insert on table "public"."job_difficulty_ratings" to "anon";

grant references on table "public"."job_difficulty_ratings" to "anon";

grant select on table "public"."job_difficulty_ratings" to "anon";

grant trigger on table "public"."job_difficulty_ratings" to "anon";

grant truncate on table "public"."job_difficulty_ratings" to "anon";

grant update on table "public"."job_difficulty_ratings" to "anon";

grant delete on table "public"."job_difficulty_ratings" to "authenticated";

grant insert on table "public"."job_difficulty_ratings" to "authenticated";

grant references on table "public"."job_difficulty_ratings" to "authenticated";

grant select on table "public"."job_difficulty_ratings" to "authenticated";

grant trigger on table "public"."job_difficulty_ratings" to "authenticated";

grant truncate on table "public"."job_difficulty_ratings" to "authenticated";

grant update on table "public"."job_difficulty_ratings" to "authenticated";

grant delete on table "public"."job_difficulty_ratings" to "service_role";

grant insert on table "public"."job_difficulty_ratings" to "service_role";

grant references on table "public"."job_difficulty_ratings" to "service_role";

grant select on table "public"."job_difficulty_ratings" to "service_role";

grant trigger on table "public"."job_difficulty_ratings" to "service_role";

grant truncate on table "public"."job_difficulty_ratings" to "service_role";

grant update on table "public"."job_difficulty_ratings" to "service_role";

grant delete on table "public"."jobs" to "anon";

grant insert on table "public"."jobs" to "anon";

grant references on table "public"."jobs" to "anon";

grant select on table "public"."jobs" to "anon";

grant trigger on table "public"."jobs" to "anon";

grant truncate on table "public"."jobs" to "anon";

grant update on table "public"."jobs" to "anon";

grant delete on table "public"."jobs" to "authenticated";

grant insert on table "public"."jobs" to "authenticated";

grant references on table "public"."jobs" to "authenticated";

grant select on table "public"."jobs" to "authenticated";

grant trigger on table "public"."jobs" to "authenticated";

grant truncate on table "public"."jobs" to "authenticated";

grant update on table "public"."jobs" to "authenticated";

grant delete on table "public"."jobs" to "service_role";

grant insert on table "public"."jobs" to "service_role";

grant references on table "public"."jobs" to "service_role";

grant select on table "public"."jobs" to "service_role";

grant trigger on table "public"."jobs" to "service_role";

grant truncate on table "public"."jobs" to "service_role";

grant update on table "public"."jobs" to "service_role";

grant delete on table "public"."payments" to "anon";

grant insert on table "public"."payments" to "anon";

grant references on table "public"."payments" to "anon";

grant select on table "public"."payments" to "anon";

grant trigger on table "public"."payments" to "anon";

grant truncate on table "public"."payments" to "anon";

grant update on table "public"."payments" to "anon";

grant delete on table "public"."payments" to "authenticated";

grant insert on table "public"."payments" to "authenticated";

grant references on table "public"."payments" to "authenticated";

grant select on table "public"."payments" to "authenticated";

grant trigger on table "public"."payments" to "authenticated";

grant truncate on table "public"."payments" to "authenticated";

grant update on table "public"."payments" to "authenticated";

grant delete on table "public"."payments" to "service_role";

grant insert on table "public"."payments" to "service_role";

grant references on table "public"."payments" to "service_role";

grant select on table "public"."payments" to "service_role";

grant trigger on table "public"."payments" to "service_role";

grant truncate on table "public"."payments" to "service_role";

grant update on table "public"."payments" to "service_role";

grant delete on table "public"."proposals" to "anon";

grant insert on table "public"."proposals" to "anon";

grant references on table "public"."proposals" to "anon";

grant select on table "public"."proposals" to "anon";

grant trigger on table "public"."proposals" to "anon";

grant truncate on table "public"."proposals" to "anon";

grant update on table "public"."proposals" to "anon";

grant delete on table "public"."proposals" to "authenticated";

grant insert on table "public"."proposals" to "authenticated";

grant references on table "public"."proposals" to "authenticated";

grant select on table "public"."proposals" to "authenticated";

grant trigger on table "public"."proposals" to "authenticated";

grant truncate on table "public"."proposals" to "authenticated";

grant update on table "public"."proposals" to "authenticated";

grant delete on table "public"."proposals" to "service_role";

grant insert on table "public"."proposals" to "service_role";

grant references on table "public"."proposals" to "service_role";

grant select on table "public"."proposals" to "service_role";

grant trigger on table "public"."proposals" to "service_role";

grant truncate on table "public"."proposals" to "service_role";

grant update on table "public"."proposals" to "service_role";

grant delete on table "public"."statuses" to "anon";

grant insert on table "public"."statuses" to "anon";

grant references on table "public"."statuses" to "anon";

grant select on table "public"."statuses" to "anon";

grant trigger on table "public"."statuses" to "anon";

grant truncate on table "public"."statuses" to "anon";

grant update on table "public"."statuses" to "anon";

grant delete on table "public"."statuses" to "authenticated";

grant insert on table "public"."statuses" to "authenticated";

grant references on table "public"."statuses" to "authenticated";

grant select on table "public"."statuses" to "authenticated";

grant trigger on table "public"."statuses" to "authenticated";

grant truncate on table "public"."statuses" to "authenticated";

grant update on table "public"."statuses" to "authenticated";

grant delete on table "public"."statuses" to "service_role";

grant insert on table "public"."statuses" to "service_role";

grant references on table "public"."statuses" to "service_role";

grant select on table "public"."statuses" to "service_role";

grant trigger on table "public"."statuses" to "service_role";

grant truncate on table "public"."statuses" to "service_role";

grant update on table "public"."statuses" to "service_role";

grant delete on table "public"."user_profiles" to "anon";

grant insert on table "public"."user_profiles" to "anon";

grant references on table "public"."user_profiles" to "anon";

grant select on table "public"."user_profiles" to "anon";

grant trigger on table "public"."user_profiles" to "anon";

grant truncate on table "public"."user_profiles" to "anon";

grant update on table "public"."user_profiles" to "anon";

grant delete on table "public"."user_profiles" to "authenticated";

grant insert on table "public"."user_profiles" to "authenticated";

grant references on table "public"."user_profiles" to "authenticated";

grant select on table "public"."user_profiles" to "authenticated";

grant trigger on table "public"."user_profiles" to "authenticated";

grant truncate on table "public"."user_profiles" to "authenticated";

grant update on table "public"."user_profiles" to "authenticated";

grant delete on table "public"."user_profiles" to "service_role";

grant insert on table "public"."user_profiles" to "service_role";

grant references on table "public"."user_profiles" to "service_role";

grant select on table "public"."user_profiles" to "service_role";

grant trigger on table "public"."user_profiles" to "service_role";

grant truncate on table "public"."user_profiles" to "service_role";

grant update on table "public"."user_profiles" to "service_role";

grant delete on table "public"."user_roles" to "anon";

grant insert on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "anon";

grant select on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant update on table "public"."user_roles" to "anon";

grant delete on table "public"."user_roles" to "authenticated";

grant insert on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "authenticated";

grant select on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant update on table "public"."user_roles" to "authenticated";

grant delete on table "public"."user_roles" to "service_role";

grant insert on table "public"."user_roles" to "service_role";

grant references on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant update on table "public"."user_roles" to "service_role";

grant delete on table "public"."withdrawal_requests" to "anon";

grant insert on table "public"."withdrawal_requests" to "anon";

grant references on table "public"."withdrawal_requests" to "anon";

grant select on table "public"."withdrawal_requests" to "anon";

grant trigger on table "public"."withdrawal_requests" to "anon";

grant truncate on table "public"."withdrawal_requests" to "anon";

grant update on table "public"."withdrawal_requests" to "anon";

grant delete on table "public"."withdrawal_requests" to "authenticated";

grant insert on table "public"."withdrawal_requests" to "authenticated";

grant references on table "public"."withdrawal_requests" to "authenticated";

grant select on table "public"."withdrawal_requests" to "authenticated";

grant trigger on table "public"."withdrawal_requests" to "authenticated";

grant truncate on table "public"."withdrawal_requests" to "authenticated";

grant update on table "public"."withdrawal_requests" to "authenticated";

grant delete on table "public"."withdrawal_requests" to "service_role";

grant insert on table "public"."withdrawal_requests" to "service_role";

grant references on table "public"."withdrawal_requests" to "service_role";

grant select on table "public"."withdrawal_requests" to "service_role";

grant trigger on table "public"."withdrawal_requests" to "service_role";

grant truncate on table "public"."withdrawal_requests" to "service_role";

grant update on table "public"."withdrawal_requests" to "service_role";


